In [ ]:
#print Statements
a=10
print("I am ",a," years old")
print("I am %d years old"%a)

I am  10  years old
I am 10 years old


In [ ]:
#Arithematic Operations
a = int(input("ENter a number:"))
b = int(input("Enter  number:"))
print("sum is {0} product is {1} Power is {2}".format(a+b,a*b,a**b))

ENter a number:13
Enter  number:2
sum is 15 product is 26 Power is 169


In [ ]:
#Take a number from the user salary if it's More than 50,000 ->10% tax print his final salary
a=int(input("Enter your salary:"))
if(a>=50000):
    t=(a*0.1)
    print("10% tax :{0:.2f} reducted".format(t))
else:
  print("no TAX reduction")
print("Your final salary is ",(a-t))

Enter your salary:50000
10% tax :5000.00 reducted
Your final salary is  45000.0


In [ ]:
#Get the salary from the user if it's >= 50,000 ->10% tax ,if it's <50000 apply 5% tax if it's more than 70000 apply 12% tax
a=int(input("Enter your salary:"))
if(a<=50000):
    t=a*0.05
    print("5% tax :{0:.2f} reducted".format(t))
elif(a<=70000):
    t=a*0.1
    print("10% tax :{0:.2f} reducted".format(t))
elif(a<=100000):
    t=a*0.12
    print("10% tax :{0:.2f} reducted".format(t))
else:
  print("Promoted")
print("Your final salary is ",(a-t))

Enter your salary:1500000000000000000
Promoted
Your final salary is  1500000000000000000


In [ ]:
a=int(input("enter number:"))
for i in range(1,11):
  print(a," x ",i," = ",a*i)

enter number:78
78  x  1  =  78
78  x  2  =  156
78  x  3  =  234
78  x  4  =  312
78  x  5  =  390
78  x  6  =  468
78  x  7  =  546
78  x  8  =  624
78  x  9  =  702
78  x  10  =  780


In [ ]:
a=int(input("enter number:"))
i=1
while(i!=11):
  print(a," x ",i," = ",a*i)
  i+=1

enter number:156
156  x  1  =  156
156  x  2  =  312
156  x  3  =  468
156  x  4  =  624
156  x  5  =  780
156  x  6  =  936
156  x  7  =  1092
156  x  8  =  1248
156  x  9  =  1404
156  x  10  =  1560


In [ ]:
l =[1,'hi',3,4.0]
print(l)

[1, 'hi', 3, 4.0]


In [2]:
#list mutability
l =[1,'hi',3,4.0]
l.append("hello")
print(l)

[1, 'hi', 3, 4.0, 'hello']


In [3]:
l2=["a","b",'c','d']l.extend(l2)
print(l)

[1, 'hi', 3, 4.0, 'hello', 'a', 'b', 'c', 'd']


In [ ]:
l.pop(2)
print(l)

[1, 'hi', 'apple', 4.0, 'hello', 'a', 'b', 'c', 'd']


In [ ]:
l.remove('b')
print(l)

[1, 'hi', 'apple', 4.0, 'hello', 'a', 'c', 'd']


In [ ]:
l.clear()
print(l)

[]


In [ ]:
#create a list of 10 integer elements save this square in new list
l=[1,45,79,74,467,4,6]
l2=[(i*i)  for i in l if i>50]
print(l2)

[6241, 5476, 218089]


In [ ]:
n=[12435465,6789,67898,789809,85856,8866]
res = [(i-i*0.10) if (i<50000) else (i-i*0.15) for i in n]
print(res)

[10570145.25, 6110.1, 57713.3, 671337.65, 72977.6, 7979.4]


In [ ]:
#dictionary
dic = {1:'Ramesh',2:'Suresh',3:'Sukesh',4:'Muskesh'}
print(dic.values())
print(dic.keys())

dic[2]

dict_values(['Ramesh', 'Suresh', 'Sukesh', 'Muskesh'])
dict_keys([1, 2, 3, 4])
Suresh


'Suresh'

In [ ]:
dic = {1:'Ramesh','Extra':{2:'Suresh',3:'Sukesh',4:'Muskesh'}}
print(dic['Extra'][2])


Suresh


In [ ]:
dic2 = (zip([1,2,3,4],['a','b','c','d']))
for i in dic2:
  print(i)

(1, 'a')
(2, 'b')
(3, 'c')
(4, 'd')


In [ ]:
dic2 = dict(zip({1,2,3,4},{'a','b','c','d'}))
print(dic2)


{1: 'b', 2: 'd', 3: 'c', 4: 'a'}


#Numpy

In [ ]:
#numpy
import numpy as np

a = np.array([1,2,3,4,5])
a.shape
a.ndim

1

In [ ]:
#numpy

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a.shape

(2, 5)

In [ ]:
#numpy

a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
              [[11,12,13,14,15],[16,17,18,19,20]]])
a.shape

(2, 2, 5)

In [ ]:

a = np.ones((2,2,2),dtype=int)
a

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:

a = np.zeros((2,2,2),dtype=int)
a

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [ ]:
a = np.eye(4,dtype=int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(8,1001,8)
a

array([   8,   16,   24,   32,   40,   48,   56,   64,   72,   80,   88,
         96,  104,  112,  120,  128,  136,  144,  152,  160,  168,  176,
        184,  192,  200,  208,  216,  224,  232,  240,  248,  256,  264,
        272,  280,  288,  296,  304,  312,  320,  328,  336,  344,  352,
        360,  368,  376,  384,  392,  400,  408,  416,  424,  432,  440,
        448,  456,  464,  472,  480,  488,  496,  504,  512,  520,  528,
        536,  544,  552,  560,  568,  576,  584,  592,  600,  608,  616,
        624,  632,  640,  648,  656,  664,  672,  680,  688,  696,  704,
        712,  720,  728,  736,  744,  752,  760,  768,  776,  784,  792,
        800,  808,  816,  824,  832,  840,  848,  856,  864,  872,  880,
        888,  896,  904,  912,  920,  928,  936,  944,  952,  960,  968,
        976,  984,  992, 1000])

In [ ]:
a = np.linspace(8,1001,8,dtype=int)
a

array([1001,  859,  718,  577,  435,  294,  153,   12])

#Tuples





In [ ]:
#Creation
t =(1,2,"a",'b')
print(type(t))

<class 'tuple'>


In [ ]:
t1=(3,4,'c','d')
t2=t+t1
print(t2)

(1, 2, 'a', 'b', 3, 4, 'c', 'd')


In [ ]:
print(t2[3])
print(t2[::-1])

b
('d', 'c', 4, 3, 'b', 'a', 2, 1)


In [ ]:
t2*2

(1, 2, 'a', 'b', 3, 4, 'c', 'd', 1, 2, 'a', 'b', 3, 4, 'c', 'd')

In [ ]:
print('d' in t2)

True


In [ ]:
print('d' not in t2)

False


#Sets

In [ ]:
s={10}
s.add(20)
s.add(30)
print(s)

{10, 20, 30}


In [ ]:
s2={40,50,60}
s.update(s2)
print(s2)

{40, 50, 60}


In [ ]:

s2.remove(50)
print(s2)

{40, 60}


In [ ]:
s2={40,60}
s2.pop()

40

In [ ]:
s1={1,2,3,4,5}
s2={4,5,6,7,8}
s1.union(s2)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
s1.intersection(s2)

{4, 5}

In [ ]:
s1.difference(s2)

{1, 2, 3}

In [ ]:
s1.symmetric_difference(s2)

{1, 2, 3, 4, 5, 60}

In [ ]:
print(s1.clear())


None
