#Array Manipulation

In [2]:
#numpy continuation
import numpy as np

In [15]:
#Array Manipulation
a = np.linspace(1,11,10,dtype=int)
print(a.shape)
b=a.reshape(5,2)#changes should be saved in a new array
print(b)

(10,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 11]]


In [18]:
a = np.linspace(1,11,10,dtype=int)
a.resize(2,5)#Changes the original array
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 11]]


In [33]:
#Array Operations
a=np.array([12,45,39,65,48,5,23,78,2]).reshape(3,3)
b=np.array([1,65,8,6,4,7,5,7,83]).reshape(3,3)
#We cannot perform arithematic operation on list elements but we can perform on lists
print(f"Subtraction of a and b is {a-b}")
print(f"Addition of a and b is {a+b}")
print(f"One on One Multiplication of a and b is {a+b}")
print(f"Matrix Multiplication of a and b is {a@b}")

Subtraction of a and b is [[ 11 -20  31]
 [ 59  44  -2]
 [ 18  71 -81]]
Addition of a and b is [[ 13 110  47]
 [ 71  52  12]
 [ 28  85  85]]
Multiplication of a and b is [[ 477 1233 3648]
 [ 378 4452 1271]
 [ 501 1821  896]]


In [43]:
#min and max function in array
a=np.arange(1,10).reshape(3,3)
#b=np.arange(1,10).reshape(3,3)
print(f"Max of the array is {a.min()}")
print(f"Max of each column is {a.min(axis=0)}")
print(f"Max of each row is {a.min(axis=1)}")

Max of the array is 1
Max of each column is [1 2 3]
Max of each row is [1 4 7]


In [44]:
a=np.arange(1,10).reshape(3,3)
#b=np.arange(1,10).reshape(3,3)
print(f"Max of the array is {a.max()}")
print(f"Max of each column is {a.max(axis=0)}")
print(f"Max of each row is {a.max(axis=1)}")

Max of the array is 9
Max of each column is [7 8 9]
Max of each row is [3 6 9]


In [53]:
#Joining arrays(Stacking)
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
print(f"Vertical stack on top of another is\n {np.vstack((a,b))} ")
print(f"Horizontal stack one beside of another is\n {np.hstack((a,b))}")

Vertical stack on top of another is
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]] 
Horizontal stack one beside of another is
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [59]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
print(f" {np.stack((a,b),axis=0)}")
print("\n\n")
print(f" {np.stack((a,b),axis=1)}")

 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]



 [[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]

 [[ 7  8  9]
  [17 18 19]]]


In [70]:
a=np.arange(1,25).reshape(2,3,4)
#b=np.arange(25,51).reshape(2,2,2)
print(a)
print("\nAfter dstack \n")
print(f"{np.dstack((a))}")
#no of groups -> no of column
#no of rows -> no of groups
#no of columns -> no of rows

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

After dstack 

[[[ 1 13]
  [ 2 14]
  [ 3 15]
  [ 4 16]]

 [[ 5 17]
  [ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]
  [12 24]]]


In [101]:
#spliting the arrays
a=np.arange(1,25).reshape(6,4)
print(a,end="\n\n")
print(np.vsplit(a,(1,4,5)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[array([[1, 2, 3, 4]]), array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20]]), array([[21, 22, 23, 24]])]


In [100]:
a=np.arange(1,25).reshape(4,6)
print(a,end="\n\n")
print(np.hsplit(a,(2,5)))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]]), array([[ 6],
       [12],
       [18],
       [24]])]


In [103]:
#arsmax() gives the index of max ele in array
a=np.arange(1,25).reshape(4,6)
print(a.argmax())

23


In [106]:
#arsmax() gives the index of max ele in array
a=np.arange(1,25).reshape(4,6)
print(a)
print(a.argmax(axis=0))#vertical

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[3 3 3 3 3 3]


In [105]:
#arsmax() gives the index of max ele in array
a=np.arange(1,25).reshape(4,6)
print(a.argmax(axis=1))#horizontal

[5 5 5 5]


In [114]:
#arsmax() gives the index of max ele in array
a=np.array([[12,325,65,6,89],[54,36,54,78,87],[32,3,54,67,8]])
print(a)
print(a.argmin(axis=1))#horizontal

[[ 12 325  65   6  89]
 [ 54  36  54  78  87]
 [ 32   3  54  67   8]]
[3 1 1]


In [115]:
#arsmax() gives the index of max ele in array
a=np.array([[12,325,65,6,89],[54,36,54,78,87],[32,3,54,67,8]])
print(a)
print(a.argmin(axis=0))#vertical

[[ 12 325  65   6  89]
 [ 54  36  54  78  87]
 [ 32   3  54  67   8]]
[0 2 1 0 2]


#Statistics

In [120]:
#
a=np.arange(1,10).reshape(3,3)
print(f"Mean of the array is {np.mean(a)}")
print(f"Mean of the array is {np.median(a)}")
print(f"Mean of the array is {np.var(a)}")
print(f"Mean of the array is {np.std(a)}")

Mean of the array is 5.0
Mean of the array is 5.0
Mean of the array is 6.666666666666667
Mean of the array is 2.581988897471611


In [122]:
p = np.pi
print(p)

3.141592653589793


In [126]:
p = np.pi
dp=np.rad2deg(p)
print(dp)

180.0


In [128]:
a=np.array([p/4,p/2,p/6])
np.rad2deg(a)


array([45., 90., 30.])

In [129]:
a=np.array([p/4,p/2,p/6])
np.deg2rad(a)


array([0.01370778, 0.02741557, 0.00913852])

In [133]:
a=np.array([p/4,p/2,p/6,0])
print(f"sin of array a is {np.sin(a)}")
print(f"sin of array a is {np.tan(a)}")
print(f"sin of array a is {np.cos(a)}")
print(f"sin of array a is {np.cot(a)}")

sin of array a is [0.70710678 1.         0.5        0.        ]
sin of array a is [1.00000000e+00 1.63312394e+16 5.77350269e-01 0.00000000e+00]
sin of array a is [7.07106781e-01 6.12323400e-17 8.66025404e-01 1.00000000e+00]


#Searching

In [144]:
a=np.array([1,23,345,65,56,25])
print(np.where(a%5==0))

(array([2, 3, 5]),)


In [142]:
#searchsorted
#given the position of the index after sorting the array
a=np.array([3,54,54,65,7,43])
print(np.searchsorted(a,7))

1


#Algebra

In [156]:
a=np.arange(1,6)
b=np.arange(11,16)
print(a,b,sep='\n')
print(f"Additon of using function is {np.add(a,b)}")
print(f"Additon of using function is {np.subtract(a,b)}")
print(f"Additon of using function is {np.sort(a)}")
print(f"Additon of using function is {np.diff(a)}")

[1 2 3 4 5]
[11 12 13 14 15]
Additon of using function is [12 14 16 18 20]
Additon of using function is [-10 -10 -10 -10 -10]
Additon of using function is [1 2 3 4 5]
Additon of using function is [1 1 1 1]


In [157]:
#set operations on np arrays
print(f"Additon of using function is {np.setdiff1d(a,b)}")
print(f"Additon of using function is {np.intersect1d(a,b)}")
print(f"Additon of using function is {np.union1d(a,b)}")

Additon of using function is [1 2 3 4 5]
Additon of using function is []
Additon of using function is [ 1  2  3  4  5 11 12 13 14 15]


#Rounding

In [164]:
a=np.array([1.232,12.123,23.5234])
print
print(f"Trucate {np.trunc(a)}")# to Lowest
print(f"Around {np.around(a,2)}")#round off with given decimal points


Trucate [ 1. 12. 23.]
Around [ 1.23 12.12 23.52]
ceil [ 2. 13. 24.]
fix [ 1. 12. 23.]


In [165]:
print(f"ceil {np.ceil(a)}")#upper values
print(f"fix {np.fix(a)}")#to lowest similar to trunc

ceil [ 2. 13. 24.]
fix [ 1. 12. 23.]


#More mathematical Functions


In [171]:
a=np.array([1,21,32,34])
print(np.cumsum(a))

[ 1 22 54 88]


In [173]:
print(np.cumprod(a))

[    1    21   672 22848]


In [176]:
print(np.lcm.reduce(a))
print(np.gcd.reduce(a))


11424
1


#Random Module

In [177]:
from numpy import random as rd

In [180]:
a=rd.rand(10)
print(a)

[0.0382498  0.85954361 0.16454689 0.69244705 0.07117971 0.20795407
 0.86702121 0.61338126 0.21413129 0.09476149]


In [183]:
a=rd.randint(10)
print(a)

3


In [192]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.inner(a,b))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.outer(a,b))